spring.application.name=springboot

server.port=8090



#viewresolver


spring.mvc.view.prefix=/WEB-INF/views/


spring.mvc.view.suffix=.jsp


spring.mvc.static-path-pattern=/static/**


# UTF-8 được xử lý bởi EncodingConfig
spring.servlet.encoding.enabled=false

# JSP / Jasper encoding
server.servlet.jsp.init-parameters.javaEncoding=UTF-8

# Tomcat connector
server.tomcat.uri-encoding=UTF-8


# SQL Server
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=webst2;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=huy210906
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Tu dong cap nhat cau truc bang khi hoc
spring.jpa.hibernate.ddl-auto=update

# Hien SQL trong Console de quan sat
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# Thu muc luu anh
app.upload-dir=uploads/categories

# Gioi han upload
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=6MB